BASE_FOLDR = "E:/New Data FCN/"
STATION = "E:/New Data FCN/Station.csv"
CATALOG = "E:/New Data FCN/Catalog6.csv"
DURATION = 400
SAMPLING = 50
REGION = [45, 47, 33, 36, 0, 30]
LONGITUDE_DELTA = 0.02
LATITUDE_DELTA = 0.02
DEPTH_DELTA = 1
DELTA = (LONGITUDE_DELTA, LATITUDE_DELTA, DEPTH_DELTA)

BATCH_SIZE = 32
IMAGE_LABELS_FILE="E:/New Data FCN/data/labels"
IMAGE_FILES_PATH="E:/New Data FCN/data/images"